# Generated by Django 5.1.2 on 2024-11-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pin',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
