# Generated by Django 5.1.2 on 2024-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_book_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('pin', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
